
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var d;d||(d=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});d.quit=function(a){if(d.onExit)d.onExit(a);throw new ca(a);};d.exit=da;ea=h=function(){};var fa={},m;for(m in d)d.hasOwnProperty(m)&&(fa[m]=d[m]);var ha=[],ia="./this.program";function ja(a,b){throw b;}var ka=!1,u=!1,w=!1,la=!1;ka="object"===typeof window;u="function"===typeof importScripts;w="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;
la=!ka&&!w&&!u;var y="",B,ma,na,oa,pa;
if(w)y=u?require("path").dirname(y)+"/":__dirname+"/",B=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},na=function(a){a=B(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/")),ha=process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;}),process.on("unhandledRejection",C),ja=function(a){process.exit(a)},d.inspect=
function(){return"[Emscripten Module object]"};else if(la)"undefined"!=typeof read&&(B=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ha=scriptArgs:"undefined"!=typeof arguments&&(ha=arguments),"function"===typeof quit&&(ja=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(ka||u)u?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="",B=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ma=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var ea=d.print||console.log.bind(console),h=d.printErr||console.warn.bind(console);for(m in fa)fa.hasOwnProperty(m)&&(d[m]=fa[m]);fa=null;d.arguments&&(ha=d.arguments);d.thisProgram&&(ia=d.thisProgram);d.quit&&(ja=d.quit);var qa=0,ra;d.wasmBinary&&(ra=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!1;
"object"!==typeof WebAssembly&&C("no native wasm support detected");var sa,ta=!1;function assert(a,b){a||C("Assertion failed: "+b)}function ua(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function va(a,b,c,e){var f={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var v=(n.length<<2)+1;q=wa(v);E(n,F,q,v)}return q},array:function(n){var q=wa(n.length);H.set(n,q);return q}},g=ua(a),l=[];a=0;if(e)for(var p=0;p<e.length;p++){var r=f[c[p]];r?(0===a&&(a=I()),l[p]=r(e[p])):l[p]=e[p]}c=g.apply(null,l);c=function(n){return"string"===b?K(n):"boolean"===b?!!n:n}(c);0!==a&&L(a);return c}var xa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function M(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&xa)return xa.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function K(a){return a?M(F,a,void 0):""}
function E(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function ya(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function za(a){var b=ya(a)+1,c=Aa(b);c&&E(a,H,c,b);return c}function Ba(a){var b=ya(a)+1,c=wa(b);E(a,H,c,b);return c}function Ca(a,b,c){for(var e=0;e<a.length;++e)H[b++>>0]=a.charCodeAt(e);c||(H[b>>0]=0)}var Fa,H,F,Ga,N,Ha,Ia,O,Ja=[],Ka=[],La=[],Ma=[],Na=[];function Oa(){var a=d.preRun.shift();Ja.unshift(a)}
var P=0,Pa=null,Ra=null;function Sa(){P++;d.monitorRunDependencies&&d.monitorRunDependencies(P)}function Ta(){P--;d.monitorRunDependencies&&d.monitorRunDependencies(P);if(0==P&&(null!==Pa&&(clearInterval(Pa),Pa=null),Ra)){var a=Ra;Ra=null;a()}}d.preloadedImages={};d.preloadedAudios={};function C(a){if(d.onAbort)d.onAbort(a);h(a);ta=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Ua(){return Q.startsWith("data:application/octet-stream;base64,")}var Q;Q="ffmpeg-core.wasm";if(!Ua()){var Wa=Q;Q=d.locateFile?d.locateFile(Wa,y):y+Wa}function Xa(){var a=Q;try{if(a==Q&&ra)return new Uint8Array(ra);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function Ya(){if(!ra&&(ka||u)){if("function"===typeof fetch&&!Q.startsWith("file://"))return fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Xa()});if(ma)return new Promise(function(a,b){ma(Q,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Xa()})}var R,S;
function Za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Sc;"number"===typeof c?void 0===b.lb?O.get(c)():O.get(c)(b.lb):c(void 0===b.lb?null:b.lb)}}}var $a=0;
function ab(a,b){a=new Date(1E3*N[a>>2]);N[b>>2]=a.getUTCSeconds();N[b+4>>2]=a.getUTCMinutes();N[b+8>>2]=a.getUTCHours();N[b+12>>2]=a.getUTCDate();N[b+16>>2]=a.getUTCMonth();N[b+20>>2]=a.getUTCFullYear()-1900;N[b+24>>2]=a.getUTCDay();N[b+36>>2]=0;N[b+32>>2]=0;N[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;ab.Db||(ab.Db=za("GMT"));N[b+40>>2]=ab.Db;return b}
function bb(){function a(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}if(!cb){cb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),e=new Date(b,6,1);b=c.getTimezoneOffset();var f=e.getTimezoneOffset(),g=Math.max(b,f);N[db()>>2]=60*g;N[eb()>>2]=Number(b!=f);c=a(c);e=a(e);c=za(c);e=za(e);f<b?(N[T()>>2]=c,N[T()+4>>2]=e):(N[T()>>2]=e,N[T()+4>>2]=c)}}var cb;
function fb(a,b){bb();a=new Date(1E3*N[a>>2]);N[b>>2]=a.getSeconds();N[b+4>>2]=a.getMinutes();N[b+8>>2]=a.getHours();N[b+12>>2]=a.getDate();N[b+16>>2]=a.getMonth();N[b+20>>2]=a.getFullYear()-1900;N[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);N[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;N[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(e!=c&&a.getTimezoneOffset()==Math.min(c,e))|0;N[b+32>>2]=a;a=N[T()+(a?4:0)>>2];
N[b+40>>2]=a;return b}function gb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function U(a){if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function jb(a,b){return hb(a+"/"+b)}
function kb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(w)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function V(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:W.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function lb(a,b){function c(l){for(var p=0;p<l.length&&""===l[p];p++);for(var r=l.length-1;0<=r&&""===l[r];r--);return p>r?[]:l.slice(p,r-p+1)}a=V(a).substr(1);b=V(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var mb=[];function nb(a,b){mb[a]={input:[],output:[],Qa:b};W.Ab(a,ob)}
var ob={open:function(a){var b=mb[a.node.rdev];if(!b)throw new W.na(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Qa.flush(a.tty)},flush:function(a){a.tty.Qa.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.Qa.Ob)throw new W.na(60);for(var f=0,g=0;g<e;g++){try{var l=a.tty.Qa.Ob(a.tty)}catch(p){throw new W.na(29);}if(void 0===l&&0===f)throw new W.na(6);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.Qa.xb)throw new W.na(60);
try{for(var f=0;f<e;f++)a.tty.Qa.xb(a.tty,b[c+f])}catch(g){throw new W.na(29);}e&&(a.node.timestamp=Date.now());return f}},qb={Ob:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.Pa?Buffer.Pa(256):new Buffer(256),e=0;try{e=oa.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},xb:function(a,b){null===b||10===b?(ea(M(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(M(a.output,0)),a.output=[])}},rb={xb:function(a,b){null===b||10===b?(h(M(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(M(a.output,0)),a.output=[])}},X={Ea:null,ua:function(){return X.createNode(null,
"/",16895,0)},createNode:function(a,b,c,e){if(W.rc(c)||W.isFIFO(c))throw new W.na(63);X.Ea||(X.Ea={dir:{node:{Ba:X.oa.Ba,xa:X.oa.xa,lookup:X.oa.lookup,Fa:X.oa.Fa,rename:X.oa.rename,unlink:X.oa.unlink,rmdir:X.oa.rmdir,readdir:X.oa.readdir,symlink:X.oa.symlink},stream:{za:X.qa.za}},file:{node:{Ba:X.oa.Ba,xa:X.oa.xa},stream:{za:X.qa.za,read:X.qa.read,write:X.qa.write,Ta:X.qa.Ta,Xa:X.qa.Xa,$a:X.qa.$a}},link:{node:{Ba:X.oa.Ba,xa:X.oa.xa,readlink:X.oa.readlink},stream:{}},Fb:{node:{Ba:X.oa.Ba,xa:X.oa.xa},
stream:W.ec}});c=W.createNode(a,b,c,e);W.va(c.mode)?(c.oa=X.Ea.dir.node,c.qa=X.Ea.dir.stream,c.pa={}):W.isFile(c.mode)?(c.oa=X.Ea.file.node,c.qa=X.Ea.file.stream,c.ta=0,c.pa=null):W.Ka(c.mode)?(c.oa=X.Ea.link.node,c.qa=X.Ea.link.stream):W.Va(c.mode)&&(c.oa=X.Ea.Fb.node,c.qa=X.Ea.Fb.stream);c.timestamp=Date.now();a&&(a.pa[b]=c,a.timestamp=c.timestamp);return c},Tc:function(a){return a.pa?a.pa.subarray?a.pa.subarray(0,a.ta):new Uint8Array(a.pa):new Uint8Array(0)},Kb:function(a,b){var c=a.pa?a.pa.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.pa,a.pa=new Uint8Array(b),0<a.ta&&a.pa.set(c.subarray(0,a.ta),0))},Dc:function(a,b){if(a.ta!=b)if(0==b)a.pa=null,a.ta=0;else{var c=a.pa;a.pa=new Uint8Array(b);c&&a.pa.set(c.subarray(0,Math.min(b,a.ta)));a.ta=b}},oa:{Ba:function(a){var b={};b.dev=W.Va(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;W.va(a.mode)?b.size=4096:W.isFile(a.mode)?b.size=a.ta:W.Ka(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.cc=4096;b.blocks=Math.ceil(b.size/b.cc);return b},xa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.Dc(a,b.size)},lookup:function(){throw W.ob[44];},Fa:function(a,b,c,e){return X.createNode(a,b,c,e)},rename:function(a,b,c){if(W.va(a.mode)){try{var e=W.Ca(b,c)}catch(g){}if(e)for(var f in e.pa)throw new W.na(55);}delete a.parent.pa[a.name];
a.parent.timestamp=Date.now();a.name=c;b.pa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.pa[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=W.Ca(a,b),e;for(e in c.pa)throw new W.na(55);delete a.pa[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.pa)a.pa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!W.Ka(a.mode))throw new W.na(28);return a.link}},
qa:{read:function(a,b,c,e,f){var g=a.node.pa;if(f>=a.node.ta)return 0;a=Math.min(a.node.ta-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.pa||a.pa.subarray)){if(g)return a.pa=b.subarray(c,c+e),a.ta=e;if(0===a.ta&&0===f)return a.pa=b.slice(c,c+e),a.ta=e;if(f+e<=a.ta)return a.pa.set(b.subarray(c,c+e),f),e}X.Kb(a,f+e);if(a.pa.subarray&&b.subarray)a.pa.set(b.subarray(c,
c+e),f);else for(g=0;g<e;g++)a.pa[f+g]=b[c+g];a.ta=Math.max(a.ta,f+e);return e},za:function(a,b,c){1===c?b+=a.position:2===c&&W.isFile(a.node.mode)&&(b+=a.node.ta);if(0>b)throw new W.na(28);return b},Ta:function(a,b,c){X.Kb(a.node,b+c);a.node.ta=Math.max(a.node.ta,b+c)},Xa:function(a,b,c,e,f,g){if(0!==b)throw new W.na(28);if(!W.isFile(a.node.mode))throw new W.na(43);a=a.node.pa;if(g&2||a.buffer!==Fa){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;g=
65536*Math.ceil(c/65536);for(b=Aa(g);c<g;)H[b+c++]=0;c=b;if(!c)throw new W.na(48);H.set(a,c)}else e=!1,c=a.byteOffset;return{Zc:c,Lc:e}},$a:function(a,b,c,e,f){if(!W.isFile(a.node.mode))throw new W.na(43);if(f&2)return 0;X.qa.write(a,b,0,e,c,!1);return 0}}},W={root:null,Za:[],Ib:{},streams:[],wc:1,Da:null,Hb:"/",rb:!1,Sb:!0,wa:{},Wb:{Ub:{Zb:1,$b:2}},na:null,ob:{},oc:null,fb:0,sa:function(a,b){a=V(W.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={nb:!0,zb:0},e;for(e in c)void 0===b[e]&&(b[e]=
c[e]);if(8<b.zb)throw new W.na(32);a=gb(a.split("/").filter(function(l){return!!l}),!1);var f=W.root;c="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=W.Ca(f,a[e]);c=jb(c,a[e]);W.La(f)&&(!g||g&&b.nb)&&(f=f.Ya.root);if(!g||b.Aa)for(g=0;W.Ka(f.mode);)if(f=W.readlink(c),c=V(ib(c),f),f=W.sa(c,{zb:b.zb}).node,40<g++)throw new W.na(32);}return{path:c,node:f}},Ha:function(a){for(var b;;){if(W.bb(a))return a=a.ua.Tb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},
qb:function(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%W.Da.length},Qb:function(a){var b=W.qb(a.parent.id,a.name);a.Na=W.Da[b];W.Da[b]=a},Rb:function(a){var b=W.qb(a.parent.id,a.name);if(W.Da[b]===a)W.Da[b]=a.Na;else for(b=W.Da[b];b;){if(b.Na===a){b.Na=a.Na;break}b=b.Na}},Ca:function(a,b){var c=W.tc(a);if(c)throw new W.na(c,a);for(c=W.Da[W.qb(a.id,b)];c;c=c.Na){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return W.lookup(a,b)},createNode:function(a,b,c,
e){a=new W.Xb(a,b,c,e);W.Qb(a);return a},mb:function(a){W.Rb(a)},bb:function(a){return a===a.parent},La:function(a){return!!a.Ya},isFile:function(a){return 32768===(a&61440)},va:function(a){return 16384===(a&61440)},Ka:function(a){return 40960===(a&61440)},Va:function(a){return 8192===(a&61440)},rc:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},pc:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},vc:function(a){var b=W.pc[a];
if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Lb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Ia:function(a,b){if(W.Sb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},tc:function(a){var b=W.Ia(a,"x");return b?b:a.oa.lookup?0:2},wb:function(a,b){try{return W.Ca(a,b),20}catch(c){}return W.Ia(a,"wx")},cb:function(a,b,c){try{var e=W.Ca(a,b)}catch(f){return f.ra}if(a=
W.Ia(a,"wx"))return a;if(c){if(!W.va(e.mode))return 54;if(W.bb(e)||W.Ha(e)===W.cwd())return 10}else if(W.va(e.mode))return 31;return 0},uc:function(a,b){return a?W.Ka(a.mode)?32:W.va(a.mode)&&("r"!==W.Lb(b)||b&512)?31:W.Ia(a,W.Lb(b)):44},Yb:4096,xc:function(a,b){b=b||W.Yb;for(a=a||0;a<=b;a++)if(!W.streams[a])return a;throw new W.na(33);},Oa:function(a){return W.streams[a]},mc:function(a,b,c){W.jb||(W.jb=function(){},W.jb.prototype={object:{get:function(){return this.node},set:function(g){this.node=
g}}});var e=new W.jb,f;for(f in a)e[f]=a[f];a=e;b=W.xc(b,c);a.fd=b;return W.streams[b]=a},fc:function(a){W.streams[a]=null},ec:{open:function(a){a.qa=W.qc(a.node.rdev).qa;a.qa.open&&a.qa.open(a)},za:function(){throw new W.na(70);}},vb:function(a){return a>>8},Vc:function(a){return a&255},Ma:function(a,b){return a<<8|b},Ab:function(a,b){W.Ib[a]={qa:b}},qc:function(a){return W.Ib[a]},Nb:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Za)}return b},Vb:function(a,b){function c(l){W.fb--;
return b(l)}function e(l){if(l){if(!e.nc)return e.nc=!0,c(l)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);W.fb++;1<W.fb&&h("warning: "+W.fb+" FS.syncfs operations in flight at once, probably just doing extra work");var f=W.Nb(W.root.ua),g=0;f.forEach(function(l){if(!l.type.Vb)return e(null);l.type.Vb(l,a,e)})},ua:function(a,b,c){var e="/"===c,f=!c;if(e&&W.root)throw new W.na(10);if(!e&&!f){var g=W.sa(c,{nb:!1});c=g.path;g=g.node;if(W.La(g))throw new W.na(10);if(!W.va(g.mode))throw new W.na(54);
}b={type:a,Yc:b,Tb:c,Za:[]};a=a.ua(b);a.ua=b;b.root=a;e?W.root=a:g&&(g.Ya=b,g.ua&&g.ua.Za.push(b));return a},bd:function(a){a=W.sa(a,{nb:!1});if(!W.La(a.node))throw new W.na(28);a=a.node;var b=a.Ya,c=W.Nb(b);Object.keys(W.Da).forEach(function(e){for(e=W.Da[e];e;){var f=e.Na;c.includes(e.ua)&&W.mb(e);e=f}});a.Ya=null;a.ua.Za.splice(a.ua.Za.indexOf(b),1)},lookup:function(a,b){return a.oa.lookup(a,b)},Fa:function(a,b,c){var e=W.sa(a,{parent:!0}).node;a=U(a);if(!a||"."===a||".."===a)throw new W.na(28);
var f=W.wb(e,a);if(f)throw new W.na(f);if(!e.oa.Fa)throw new W.na(63);return e.oa.Fa(e,a,b,c)},create:function(a,b){return W.Fa(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return W.Fa(a,(void 0!==b?b:511)&1023|16384,0)},Wc:function(a,b){a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{W.mkdir(c,b)}catch(f){if(20!=f.ra)throw f;}}},eb:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return W.Fa(a,b|8192,c)},symlink:function(a,b){if(!V(a))throw new W.na(44);var c=
W.sa(b,{parent:!0}).node;if(!c)throw new W.na(44);b=U(b);var e=W.wb(c,b);if(e)throw new W.na(e);if(!c.oa.symlink)throw new W.na(63);return c.oa.symlink(c,b,a)},rename:function(a,b){var c=ib(a),e=ib(b),f=U(a),g=U(b);var l=W.sa(a,{parent:!0});var p=l.node;l=W.sa(b,{parent:!0});l=l.node;if(!p||!l)throw new W.na(44);if(p.ua!==l.ua)throw new W.na(75);var r=W.Ca(p,f);e=lb(a,e);if("."!==e.charAt(0))throw new W.na(28);e=lb(b,c);if("."!==e.charAt(0))throw new W.na(55);try{var n=W.Ca(l,g)}catch(q){}if(r!==
n){c=W.va(r.mode);if(f=W.cb(p,f,c))throw new W.na(f);if(f=n?W.cb(l,g,c):W.wb(l,g))throw new W.na(f);if(!p.oa.rename)throw new W.na(63);if(W.La(r)||n&&W.La(n))throw new W.na(10);if(l!==p&&(f=W.Ia(p,"w")))throw new W.na(f);try{W.wa.willMovePath&&W.wa.willMovePath(a,b)}catch(q){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+q.message)}W.Rb(r);try{p.oa.rename(r,l,g)}catch(q){throw q;}finally{W.Qb(r)}try{if(W.wa.onMovePath)W.wa.onMovePath(a,b)}catch(q){h("FS.trackingDelegate['onMovePath']('"+
a+"', '"+b+"') threw an exception: "+q.message)}}},rmdir:function(a){var b=W.sa(a,{parent:!0}).node,c=U(a),e=W.Ca(b,c),f=W.cb(b,c,!0);if(f)throw new W.na(f);if(!b.oa.rmdir)throw new W.na(63);if(W.La(e))throw new W.na(10);try{W.wa.willDeletePath&&W.wa.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.oa.rmdir(b,c);W.mb(e);try{if(W.wa.onDeletePath)W.wa.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+
g.message)}},readdir:function(a){a=W.sa(a,{Aa:!0}).node;if(!a.oa.readdir)throw new W.na(54);return a.oa.readdir(a)},unlink:function(a){var b=W.sa(a,{parent:!0}).node,c=U(a),e=W.Ca(b,c),f=W.cb(b,c,!1);if(f)throw new W.na(f);if(!b.oa.unlink)throw new W.na(63);if(W.La(e))throw new W.na(10);try{W.wa.willDeletePath&&W.wa.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.oa.unlink(b,c);W.mb(e);try{if(W.wa.onDeletePath)W.wa.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}},readlink:function(a){a=W.sa(a).node;if(!a)throw new W.na(44);if(!a.oa.readlink)throw new W.na(28);return V(W.Ha(a.parent),a.oa.readlink(a))},stat:function(a,b){a=W.sa(a,{Aa:!b}).node;if(!a)throw new W.na(44);if(!a.oa.Ba)throw new W.na(63);return a.oa.Ba(a)},lstat:function(a){return W.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?W.sa(a,{Aa:!c}).node:a;if(!a.oa.xa)throw new W.na(63);a.oa.xa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,
b){W.chmod(a,b,!0)},fchmod:function(a,b){a=W.Oa(a);if(!a)throw new W.na(8);W.chmod(a.node,b)},chown:function(a,b,c,e){a="string"===typeof a?W.sa(a,{Aa:!e}).node:a;if(!a.oa.xa)throw new W.na(63);a.oa.xa(a,{timestamp:Date.now()})},lchown:function(a,b,c){W.chown(a,b,c,!0)},fchown:function(a,b,c){a=W.Oa(a);if(!a)throw new W.na(8);W.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new W.na(28);a="string"===typeof a?W.sa(a,{Aa:!0}).node:a;if(!a.oa.xa)throw new W.na(63);if(W.va(a.mode))throw new W.na(31);
if(!W.isFile(a.mode))throw new W.na(28);var c=W.Ia(a,"w");if(c)throw new W.na(c);a.oa.xa(a,{size:b,timestamp:Date.now()})},Rc:function(a,b){a=W.Oa(a);if(!a)throw new W.na(8);if(0===(a.flags&2097155))throw new W.na(28);W.truncate(a.node,b)},cd:function(a,b,c){a=W.sa(a,{Aa:!0}).node;a.oa.xa(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,e,f){if(""===a)throw new W.na(44);b="string"===typeof b?W.vc(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=hb(a);
try{g=W.sa(a,{Aa:!(b&131072)}).node}catch(p){}}var l=!1;if(b&64)if(g){if(b&128)throw new W.na(20);}else g=W.Fa(a,c,0),l=!0;if(!g)throw new W.na(44);W.Va(g.mode)&&(b&=-513);if(b&65536&&!W.va(g.mode))throw new W.na(54);if(!l&&(c=W.uc(g,b)))throw new W.na(c);b&512&&W.truncate(g,0);b&=-131713;e=W.mc({node:g,path:W.Ha(g),flags:b,seekable:!0,position:0,qa:g.qa,Kc:[],error:!1},e,f);e.qa.open&&e.qa.open(e);!d.logReadFiles||b&1||(W.yb||(W.yb={}),a in W.yb||(W.yb[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{W.wa.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=W.Wb.Ub.Zb),0!==(b&2097155)&&(f|=W.Wb.Ub.$b),W.wa.onOpenFile(a,f))}catch(p){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return e},close:function(a){if(W.Wa(a))throw new W.na(8);a.Ja&&(a.Ja=null);try{a.qa.close&&a.qa.close(a)}catch(b){throw b;}finally{W.fc(a.fd)}a.fd=null},Wa:function(a){return null===a.fd},za:function(a,b,c){if(W.Wa(a))throw new W.na(8);if(!a.seekable||!a.qa.za)throw new W.na(70);if(0!=c&&
1!=c&&2!=c)throw new W.na(28);a.position=a.qa.za(a,b,c);a.Kc=[];return a.position},read:function(a,b,c,e,f){if(0>e||0>f)throw new W.na(28);if(W.Wa(a))throw new W.na(8);if(1===(a.flags&2097155))throw new W.na(8);if(W.va(a.node.mode))throw new W.na(31);if(!a.qa.read)throw new W.na(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new W.na(70);b=a.qa.read(a,b,c,e,f);g||(a.position+=b);return b},write:function(a,b,c,e,f,g){if(0>e||0>f)throw new W.na(28);if(W.Wa(a))throw new W.na(8);
if(0===(a.flags&2097155))throw new W.na(8);if(W.va(a.node.mode))throw new W.na(31);if(!a.qa.write)throw new W.na(28);a.seekable&&a.flags&1024&&W.za(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new W.na(70);b=a.qa.write(a,b,c,e,f,g);l||(a.position+=b);try{if(a.path&&W.wa.onWriteToFile)W.wa.onWriteToFile(a.path)}catch(p){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+p.message)}return b},Ta:function(a,b,c){if(W.Wa(a))throw new W.na(8);
if(0>b||0>=c)throw new W.na(28);if(0===(a.flags&2097155))throw new W.na(8);if(!W.isFile(a.node.mode)&&!W.va(a.node.mode))throw new W.na(43);if(!a.qa.Ta)throw new W.na(138);a.qa.Ta(a,b,c)},Xa:function(a,b,c,e,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new W.na(2);if(1===(a.flags&2097155))throw new W.na(2);if(!a.qa.Xa)throw new W.na(43);return a.qa.Xa(a,b,c,e,f,g)},$a:function(a,b,c,e,f){return a&&a.qa.$a?a.qa.$a(a,b,c,e,f):0},Xc:function(){return 0},sb:function(a,b,c){if(!a.qa.sb)throw new W.na(59);
return a.qa.sb(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=W.open(a,b.flags);a=W.stat(a).size;var f=new Uint8Array(a);W.read(e,f,0,a,0);"utf8"===b.encoding?c=M(f,0):"binary"===b.encoding&&(c=f);W.close(e);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=W.open(a,c.flags,c.mode);if("string"===typeof b){var e=new Uint8Array(ya(b)+
1);b=E(b,e,0,e.length);W.write(a,e,0,b,void 0,c.dc)}else if(ArrayBuffer.isView(b))W.write(a,b,0,b.byteLength,void 0,c.dc);else throw Error("Unsupported data type");W.close(a)},cwd:function(){return W.Hb},chdir:function(a){a=W.sa(a,{Aa:!0});if(null===a.node)throw new W.na(44);if(!W.va(a.node.mode))throw new W.na(54);var b=W.Ia(a.node,"x");if(b)throw new W.na(b);W.Hb=a.path},ic:function(){W.mkdir("/tmp");W.mkdir("/home");W.mkdir("/home/web_user")},hc:function(){W.mkdir("/dev");W.Ab(W.Ma(1,3),{read:function(){return 0},
write:function(b,c,e,f){return f}});W.eb("/dev/null",W.Ma(1,3));nb(W.Ma(5,0),qb);nb(W.Ma(6,0),rb);W.eb("/dev/tty",W.Ma(5,0));W.eb("/dev/tty1",W.Ma(6,0));var a=kb();W.Ga("/dev","random",a);W.Ga("/dev","urandom",a);W.mkdir("/dev/shm");W.mkdir("/dev/shm/tmp")},kc:function(){W.mkdir("/proc");var a=W.mkdir("/proc/self");W.mkdir("/proc/self/fd");W.ua({ua:function(){var b=W.createNode(a,"fd",16895,73);b.oa={lookup:function(c,e){var f=W.Oa(+e);if(!f)throw new W.na(8);c={parent:null,ua:{Tb:"fake"},oa:{readlink:function(){return f.path}}};
return c.parent=c}};return b}},{},"/proc/self/fd")},lc:function(){d.stdin?W.Ga("/dev","stdin",d.stdin):W.symlink("/dev/tty","/dev/stdin");d.stdout?W.Ga("/dev","stdout",null,d.stdout):W.symlink("/dev/tty","/dev/stdout");d.stderr?W.Ga("/dev","stderr",null,d.stderr):W.symlink("/dev/tty1","/dev/stderr");W.open("/dev/stdin",0);W.open("/dev/stdout",1);W.open("/dev/stderr",1)},Jb:function(){W.na||(W.na=function(a,b){this.node=b;this.Ec=function(c){this.ra=c};this.Ec(a);this.message="FS error"},W.na.prototype=
Error(),W.na.prototype.constructor=W.na,[44].forEach(function(a){W.ob[a]=new W.na(a);W.ob[a].stack="<generic error, no stack>"}))},Fc:function(){W.Jb();W.Da=Array(4096);W.ua(X,{},"/");W.ic();W.hc();W.kc();W.oc={MEMFS:X}},Ua:function(a,b,c){W.Ua.rb=!0;W.Jb();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;W.lc()},quit:function(){W.Ua.rb=!1;var a=d._fflush;a&&a(0);for(a=0;a<W.streams.length;a++){var b=W.streams[a];b&&W.close(b)}},pb:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},
Qc:function(a,b){a=W.kb(a,b);return a.exists?a.object:null},kb:function(a,b){try{var c=W.sa(a,{Aa:!b});a=c.path}catch(f){}var e={bb:!1,exists:!1,error:0,name:null,path:null,object:null,zc:!1,Bc:null,Ac:null};try{c=W.sa(a,{parent:!0}),e.zc=!0,e.Bc=c.path,e.Ac=c.node,e.name=U(a),c=W.sa(a,{Aa:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.bb="/"===c.path}catch(f){e.error=f.ra}return e},Oc:function(a,b){a="string"===typeof a?a:W.Ha(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var e=jb(a,c);try{W.mkdir(e)}catch(f){}a=e}}return e},jc:function(a,b,c,e,f){a=jb("string"===typeof a?a:W.Ha(a),b);return W.create(a,W.pb(e,f))},Gb:function(a,b,c,e,f,g){a=b?jb("string"===typeof a?a:W.Ha(a),b):a;e=W.pb(e,f);f=W.create(a,e);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}W.chmod(f,e|146);a=W.open(f,577);W.write(a,c,0,c.length,0,g);W.close(a);W.chmod(f,e)}return f},Ga:function(a,b,c,e){a=jb("string"===typeof a?a:
W.Ha(a),b);b=W.pb(!!c,!!e);W.Ga.vb||(W.Ga.vb=64);var f=W.Ma(W.Ga.vb++,0);W.Ab(f,{open:function(g){g.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(g,l,p,r){for(var n=0,q=0;q<r;q++){try{var v=c()}catch(A){throw new W.na(29);}if(void 0===v&&0===n)throw new W.na(6);if(null===v||void 0===v)break;n++;l[p+q]=v}n&&(g.node.timestamp=Date.now());return n},write:function(g,l,p,r){for(var n=0;n<r;n++)try{e(l[p+n])}catch(q){throw new W.na(29);}r&&(g.node.timestamp=Date.now());
return n}});return W.eb(a,b,f)},Mb:function(a){if(a.tb||a.sc||a.link||a.pa)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(B)try{a.pa=pb(B(a.url),!0),a.ta=a.pa.length}catch(b){throw new W.na(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Nc:function(a,b,c,e,f){function g(){this.ub=
!1;this.Pa=[]}g.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.chunkSize;return this.Pb(n/this.chunkSize|0)[q]}};g.prototype.yc=function(n){this.Pb=n};g.prototype.Eb=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),v,A=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var k=1048576;A||(k=q);var t=this;t.yc(function(x){var D=x*k,J=(x+1)*k-1;J=Math.min(J,q-1);if("undefined"===typeof t.Pa[x]){var Qa=t.Pa;if(D>J)throw Error("invalid range ("+D+", "+J+") or no bytes requested!");if(J>q-1)throw Error("only "+q+" bytes available! programmer error!");var z=new XMLHttpRequest;z.open("GET",c,!1);q!==k&&z.setRequestHeader("Range","bytes="+D+"-"+J);"undefined"!=typeof Uint8Array&&(z.responseType="arraybuffer");z.overrideMimeType&&z.overrideMimeType("text/plain; charset=x-user-defined");
z.send(null);if(!(200<=z.status&&300>z.status||304===z.status))throw Error("Couldn't load "+c+". Status: "+z.status);D=void 0!==z.response?new Uint8Array(z.response||[]):pb(z.responseText||"",!0);Qa[x]=D}if("undefined"===typeof t.Pa[x])throw Error("doXHR failed!");return t.Pa[x]});if(n||!q)k=q=1,k=q=this.Pb(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.bc=q;this.ac=k;this.ub=!0};if("undefined"!==typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new g;Object.defineProperties(l,{length:{get:function(){this.ub||this.Eb();return this.bc}},chunkSize:{get:function(){this.ub||this.Eb();return this.ac}}});l={tb:!1,pa:l}}else l={tb:!1,url:c};var p=W.jc(a,b,l,e,f);l.pa?p.pa=l.pa:l.url&&(p.pa=null,p.url=l.url);Object.defineProperties(p,{ta:{get:function(){return this.pa.length}}});var r={};Object.keys(p.qa).forEach(function(n){var q=p.qa[n];r[n]=function(){W.Mb(p);return q.apply(null,arguments)}});r.read=function(n,q,v,A,k){W.Mb(p);n=n.node.pa;
if(k>=n.length)return 0;A=Math.min(n.length-k,A);if(n.slice)for(var t=0;t<A;t++)q[v+t]=n[k+t];else for(t=0;t<A;t++)q[v+t]=n.get(k+t);return A};p.qa=r;return p},Pc:function(a,b,c,e,f,g,l,p,r,n){function q(A){function k(x){n&&n();p||W.Gb(a,b,x,e,f,r);g&&g();Ta()}var t=!1;d.preloadPlugins.forEach(function(x){!t&&x.canHandle(v)&&(x.handle(A,v,k,function(){l&&l();Ta()}),t=!0)});t||k(A)}sb.Ua();var v=b?V(jb(a,b)):a;Sa();"string"==typeof c?sb.Mc(c,function(A){q(A)},l):q(c)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Bb:function(){return"EM_FS_"+window.location.pathname},Cb:20,Sa:"FILE_DATA",$c:function(a,b,c){b=b||function(){};c=c||function(){};var e=W.indexedDB();try{var f=e.open(W.Bb(),W.Cb)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(W.Sa)};f.onsuccess=function(){var g=f.result.transaction([W.Sa],"readwrite"),l=g.objectStore(W.Sa),p=0,r=0,n=a.length;a.forEach(function(q){q=l.put(W.kb(q).object.pa,
q);q.onsuccess=function(){p++;p+r==n&&(0==r?b():c())};q.onerror=function(){r++;p+r==n&&(0==r?b():c())}});g.onerror=c};f.onerror=c},Uc:function(a,b,c){b=b||function(){};c=c||function(){};var e=W.indexedDB();try{var f=e.open(W.Bb(),W.Cb)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var l=g.transaction([W.Sa],"readonly")}catch(v){c(v);return}var p=l.objectStore(W.Sa),r=0,n=0,q=a.length;a.forEach(function(v){var A=p.get(v);A.onsuccess=function(){W.kb(v).exists&&W.unlink(v);
W.Gb(ib(v),U(v),A.result,!0,!0,!0);r++;r+n==q&&(0==n?b():c())};A.onerror=function(){n++;r+n==q&&(0==n?b():c())}});l.onerror=c};f.onerror=c}};
function tb(a,b,c){try{var e=a(b)}catch(f){if(f&&f.node&&hb(b)!==hb(W.Ha(f.node)))return-54;throw f;}N[c>>2]=e.dev;N[c+4>>2]=0;N[c+8>>2]=e.ino;N[c+12>>2]=e.mode;N[c+16>>2]=e.nlink;N[c+20>>2]=e.uid;N[c+24>>2]=e.gid;N[c+28>>2]=e.rdev;N[c+32>>2]=0;S=[e.size>>>0,(R=e.size,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[c+40>>2]=S[0];N[c+44>>2]=S[1];N[c+48>>2]=4096;N[c+52>>2]=e.blocks;N[c+56>>2]=e.atime.getTime()/1E3|0;N[c+60>>
2]=0;N[c+64>>2]=e.mtime.getTime()/1E3|0;N[c+68>>2]=0;N[c+72>>2]=e.ctime.getTime()/1E3|0;N[c+76>>2]=0;S=[e.ino>>>0,(R=e.ino,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[c+80>>2]=S[0];N[c+84>>2]=S[1];return 0}var ub=void 0;function vb(){ub+=4;return N[ub-4>>2]}function Y(a){a=W.Oa(a);if(!a)throw new W.na(8);return a}function wb(){void 0===wb.start&&(wb.start=Date.now());return 1E3*(Date.now()-wb.start)|0}var xb;
w?xb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?xb=dateNow:xb=function(){return performance.now()};var yb={};function zb(){if(!Ab){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in yb)void 0===yb[b]?delete a[b]:a[b]=yb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ab=c}return Ab}var Ab;
function Bb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Cb(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var Db=[31,29,31,30,31,30,31,31,30,31,30,31],Eb=[31,28,31,30,31,30,31,31,30,31,30,31];function Fb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Bb(a.getFullYear())?Db:Eb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Gb(a,b,c,e){a||(a=this);this.parent=a;this.ua=a.ua;this.Ya=null;this.id=W.wc++;this.name=b;this.mode=c;this.oa={};this.qa={};this.rdev=e}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sc:{get:function(){return W.va(this.mode)}},tb:{get:function(){return W.Va(this.mode)}}});W.Xb=Gb;W.Fc();var sb;
function pb(a,b){var c=Array(ya(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Qb={a:function(a,b,c,e){C("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,e?K(e):"unknown function"])},H:function(a,b){return ab(a,b)},F:function(a,b){return fb(a,b)},M:function(a,b,c,e){try{for(var f=0,g=b?N[b>>2]:0,l=b?N[b+4>>2]:0,p=c?N[c>>2]:0,r=c?N[c+4>>2]:0,n=e?N[e>>2]:0,q=e?N[e+4>>2]:0,v=0,A=0,k=0,t=0,x=0,D=0,J=(b?N[b>>2]:0)|(c?N[c>>2]:0)|(e?N[e>>2]:0),Qa=(b?N[b+4>>2]:0)|(c?N[c+4>>2]:0)|(e?N[e+4>>2]:0),z=0;z<a;z++){var G=1<<z%32;if(32>z?J&G:Qa&G){var Da=W.Oa(z);if(!Da)throw new W.na(8);
var Ea=5;Da.qa.Cc&&(Ea=Da.qa.Cc(Da));Ea&1&&(32>z?g&G:l&G)&&(32>z?v|=G:A|=G,f++);Ea&4&&(32>z?p&G:r&G)&&(32>z?k|=G:t|=G,f++);Ea&2&&(32>z?n&G:q&G)&&(32>z?x|=G:D|=G,f++)}}b&&(N[b>>2]=v,N[b+4>>2]=A);c&&(N[c>>2]=k,N[c+4>>2]=t);e&&(N[e>>2]=x,N[e+4>>2]=D);return f}catch(Va){return"undefined"!==typeof W&&Va instanceof W.na||C(Va),-Va.ra}},O:function(a,b){try{a=K(a);if(b&-8)var c=-28;else{var e;(e=W.sa(a,{Aa:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&W.Ia(e,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==
typeof W&&f instanceof W.na||C(f),-f.ra}},l:function(a,b,c){ub=c;try{var e=Y(a);switch(b){case 0:var f=vb();return 0>f?-28:W.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=vb(),e.flags|=f,0;case 12:return f=vb(),Ga[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return N[Hb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof W.na||C(g),-g.ra}},U:function(a,b){try{var c=Y(a);return tb(W.stat,c.path,b)}catch(e){return"undefined"!==
typeof W&&e instanceof W.na||C(e),-e.ra}},I:function(a,b,c){try{var e=Y(a);e.Ja||(e.Ja=W.readdir(e.path));a=0;for(var f=W.za(e,0,1),g=Math.floor(f/280);g<e.Ja.length&&a+280<=c;){var l=e.Ja[g];if("."===l[0]){var p=1;var r=4}else{var n=W.Ca(e.node,l);p=n.id;r=W.Va(n.mode)?2:W.va(n.mode)?4:W.Ka(n.mode)?10:8}S=[p>>>0,(R=p,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[b+a>>2]=S[0];N[b+a+4>>2]=S[1];S=[280*(g+1)>>>0,(R=280*(g+
1),1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[b+a+8>>2]=S[0];N[b+a+12>>2]=S[1];Ga[b+a+16>>1]=280;H[b+a+18>>0]=r;E(l,F,b+a+19,256);a+=280;g+=1}W.za(e,280*g,0);return a}catch(q){return"undefined"!==typeof W&&q instanceof W.na||C(q),-q.ra}},L:function(a,b){try{return Ib(b,0,136),N[b>>2]=1,N[b+4>>2]=2,N[b+8>>2]=3,N[b+12>>2]=4,0}catch(c){return"undefined"!==typeof W&&c instanceof W.na||C(c),-c.ra}},o:function(a,b,c){ub=c;
try{var e=Y(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=vb();return N[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=vb(),W.sb(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:C("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof W.na||C(g),-g.ra}},V:function(a,b){try{return a=K(a),tb(W.lstat,a,b)}catch(c){return"undefined"!==
typeof W&&c instanceof W.na||C(c),-c.ra}},q:function(a,b,c){ub=c;try{var e=K(a),f=c?vb():0;return W.open(e,b,f).fd}catch(g){return"undefined"!==typeof W&&g instanceof W.na||C(g),-g.ra}},K:function(a,b,c,e){try{return e&&(N[e>>2]=-1,N[e+4>>2]=-1,N[e+8>>2]=-1,N[e+12>>2]=-1),0}catch(f){return"undefined"!==typeof W&&f instanceof W.na||C(f),-f.ra}},S:function(a,b){try{return a=K(a),b=K(b),W.rename(a,b),0}catch(c){return"undefined"!==typeof W&&c instanceof W.na||C(c),-c.ra}},P:function(a){try{return a=
K(a),W.rmdir(a),0}catch(b){return"undefined"!==typeof W&&b instanceof W.na||C(b),-b.ra}},J:function(){return 0},T:function(a,b){try{return a=K(a),tb(W.stat,a,b)}catch(c){return"undefined"!==typeof W&&c instanceof W.na||C(c),-c.ra}},R:function(a){try{return a=K(a),W.unlink(a),0}catch(b){return"undefined"!==typeof W&&b instanceof W.na||C(b),-b.ra}},B:function(){throw"longjmp";},b:function(){C()},G:wb,Q:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=xb();else return N[Hb()>>2]=28,-1;N[b>>
2]=a/1E3|0;N[b+4>>2]=a%1E3*1E6|0;return 0},N:function(){return F.length},z:function(a,b,c){F.copyWithin(a,b,b+c)},A:function(){C("OOM")},E:function(a){for(var b=xb();xb()-b<a;);},C:function(a,b){try{var c=0;zb().forEach(function(e,f){var g=b+c;N[a+4*f>>2]=g;Ca(e,g);c+=e.length+1});return 0}catch(e){return"undefined"!==typeof W&&e instanceof W.na||C(e),e.ra}},D:function(a,b){try{var c=zb();N[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});N[b>>2]=e;return 0}catch(f){return"undefined"!==
typeof W&&f instanceof W.na||C(f),f.ra}},i:function(a){da(a)},j:function(a){try{var b=Y(a);W.close(b);return 0}catch(c){return"undefined"!==typeof W&&c instanceof W.na||C(c),c.ra}},n:function(a,b){try{var c=Y(a);H[b>>0]=c.tty?2:W.va(c.mode)?3:W.Ka(c.mode)?7:4;return 0}catch(e){return"undefined"!==typeof W&&e instanceof W.na||C(e),e.ra}},p:function(a,b,c,e){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var l=N[b+(8*g+4)>>2],p=W.read(f,H,N[b+8*g>>2],l,void 0);if(0>p){var r=-1;break a}a+=p;if(p<l)break}r=a}N[e>>
2]=r;return 0}catch(n){return"undefined"!==typeof W&&n instanceof W.na||C(n),n.ra}},w:function(a,b,c,e,f){try{var g=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;W.za(g,a,e);S=[g.position>>>0,(R=g.position,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[f>>2]=S[0];N[f+4>>2]=S[1];g.Ja&&0===a&&0===e&&(g.Ja=null);return 0}catch(l){return"undefined"!==typeof W&&l instanceof W.na||C(l),l.ra}},
k:function(a,b,c,e){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var l=W.write(f,H,N[b+8*g>>2],N[b+(8*g+4)>>2],void 0);if(0>l){var p=-1;break a}a+=l}p=a}N[e>>2]=p;return 0}catch(r){return"undefined"!==typeof W&&r instanceof W.na||C(r),r.ra}},c:function(){return qa},e:function(a){var b=Date.now();N[a>>2]=b/1E3|0;N[a+4>>2]=b%1E3*1E3|0;return 0},m:ab,f:Jb,W:Kb,x:Lb,X:Mb,s:Nb,h:Ob,y:Pb,v:fb,u:function(a){bb();var b=new Date(N[a+20>>2]+1900,N[a+16>>2],N[a+12>>2],N[a+8>>2],N[a+4>>2],N[a>>2],0),c=N[a+32>>2],e=b.getTimezoneOffset(),
f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=f.getTimezoneOffset(),p=Math.min(l,g);0>c?N[a+32>>2]=Number(g!=l&&p==e):0<c!=(p==e)&&(g=Math.max(l,g),b.setTime(b.getTime()+6E4*((0<c?p:g)-e)));N[a+24>>2]=b.getDay();N[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;N[a>>2]=b.getSeconds();N[a+4>>2]=b.getMinutes();N[a+8>>2]=b.getHours();N[a+12>>2]=b.getDate();N[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},d:function(a){qa=a},g:function(){return 0},t:function(a,b,
c,e){function f(k,t,x){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=x[0]+k;return k}function g(k,t){return f(k,t,"0")}function l(k,t){function x(J){return 0>J?-1:0<J?1:0}var D;0===(D=x(k.getFullYear()-t.getFullYear()))&&0===(D=x(k.getMonth()-t.getMonth()))&&(D=x(k.getDate()-t.getDate()));return D}function p(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),
0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function r(k){k=Fb(new Date(k.ya+1900,0,1),k.ib);var t=new Date(k.getFullYear()+1,0,4),x=p(new Date(k.getFullYear(),0,4));t=p(t);return 0>=l(x,k)?0>=l(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=N[e+40>>2];e={Ic:N[e>>2],Hc:N[e+4>>2],gb:N[e+8>>2],ab:N[e+12>>2],Ra:N[e+16>>2],ya:N[e+20>>2],hb:N[e+24>>2],ib:N[e+28>>2],ad:N[e+32>>2],Gc:N[e+36>>2],Jc:n?K(n):""};c=K(c);n={"%c":"%a %b %d %H:%M:%S %Y",
"%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");
n={"%a":function(k){return v[k.hb].substring(0,3)},"%A":function(k){return v[k.hb]},"%b":function(k){return A[k.Ra].substring(0,3)},"%B":function(k){return A[k.Ra]},"%C":function(k){return g((k.ya+1900)/100|0,2)},"%d":function(k){return g(k.ab,2)},"%e":function(k){return f(k.ab,2," ")},"%g":function(k){return r(k).toString().substring(2)},"%G":function(k){return r(k)},"%H":function(k){return g(k.gb,2)},"%I":function(k){k=k.gb;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.ab+Cb(Bb(k.ya+
1900)?Db:Eb,k.Ra-1),3)},"%m":function(k){return g(k.Ra+1,2)},"%M":function(k){return g(k.Hc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.gb&&12>k.gb?"AM":"PM"},"%S":function(k){return g(k.Ic,2)},"%t":function(){return"\t"},"%u":function(k){return k.hb||7},"%U":function(k){var t=new Date(k.ya+1900,0,1),x=0===t.getDay()?t:Fb(t,7-t.getDay());k=new Date(k.ya+1900,k.Ra,k.ab);return 0>l(x,k)?g(Math.ceil((31-x.getDate()+(Cb(Bb(k.getFullYear())?Db:Eb,k.getMonth()-1)-31)+k.getDate())/7),2):
0===l(x,t)?"01":"00"},"%V":function(k){var t=new Date(k.ya+1901,0,4),x=p(new Date(k.ya+1900,0,4));t=p(t);var D=Fb(new Date(k.ya+1900,0,1),k.ib);return 0>l(D,x)?"53":0>=l(t,D)?"01":g(Math.ceil((x.getFullYear()<k.ya+1900?k.ib+32-x.getDate():k.ib+1-x.getDate())/7),2)},"%w":function(k){return k.hb},"%W":function(k){var t=new Date(k.ya,0,1),x=1===t.getDay()?t:Fb(t,0===t.getDay()?1:7-t.getDay()+1);k=new Date(k.ya+1900,k.Ra,k.ab);return 0>l(x,k)?g(Math.ceil((31-x.getDate()+(Cb(Bb(k.getFullYear())?Db:Eb,
k.getMonth()-1)-31)+k.getDate())/7),2):0===l(x,t)?"01":"00"},"%y":function(k){return(k.ya+1900).toString().substring(2)},"%Y":function(k){return k.ya+1900},"%z":function(k){k=k.Gc;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Jc},"%%":function(){return"%"}};for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](e)));q=pb(c,!1);if(q.length>b)return 0;H.set(q,a);return q.length-1},r:function(a){var b=Date.now()/1E3|0;a&&(N[a>>
2]=b);return b}};
(function(){function a(f){d.asm=f.exports;sa=d.asm.Y;Fa=f=sa.buffer;d.HEAP8=H=new Int8Array(f);d.HEAP16=Ga=new Int16Array(f);d.HEAP32=N=new Int32Array(f);d.HEAPU8=F=new Uint8Array(f);d.HEAPU16=new Uint16Array(f);d.HEAPU32=new Uint32Array(f);d.HEAPF32=Ha=new Float32Array(f);d.HEAPF64=Ia=new Float64Array(f);O=d.asm.aa;Ka.unshift(d.asm.Z);Ta()}function b(f){a(f.instance)}function c(f){return Ya().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);
C(g)})}var e={a:Qb};Sa();if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ra||"function"!==typeof WebAssembly.instantiateStreaming||Ua()||Q.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(ba);return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.Z).apply(null,arguments)};var Ib=d._memset=function(){return(Ib=d._memset=d.asm._).apply(null,arguments)},Aa=d._malloc=function(){return(Aa=d._malloc=d.asm.$).apply(null,arguments)},Hb=d.___errno_location=function(){return(Hb=d.___errno_location=d.asm.ba).apply(null,arguments)};d._fflush=function(){return(d._fflush=d.asm.ca).apply(null,arguments)};
d._main=function(){return(d._main=d.asm.da).apply(null,arguments)};
var T=d.__get_tzname=function(){return(T=d.__get_tzname=d.asm.ea).apply(null,arguments)},eb=d.__get_daylight=function(){return(eb=d.__get_daylight=d.asm.fa).apply(null,arguments)},db=d.__get_timezone=function(){return(db=d.__get_timezone=d.asm.ga).apply(null,arguments)},I=d.stackSave=function(){return(I=d.stackSave=d.asm.ha).apply(null,arguments)},L=d.stackRestore=function(){return(L=d.stackRestore=d.asm.ia).apply(null,arguments)},wa=d.stackAlloc=function(){return(wa=d.stackAlloc=d.asm.ja).apply(null,
arguments)},Z=d._setThrew=function(){return(Z=d._setThrew=d.asm.ka).apply(null,arguments)},Rb=d.dynCall_vijjjid=function(){return(Rb=d.dynCall_vijjjid=d.asm.la).apply(null,arguments)},Sb=d.dynCall_iiiijj=function(){return(Sb=d.dynCall_iiiijj=d.asm.ma).apply(null,arguments)};function Jb(a,b,c){var e=I();try{return O.get(a)(b,c)}catch(f){L(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Mb(a,b){var c=I();try{O.get(a)(b)}catch(e){L(c);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}
function Ob(a,b,c,e,f){var g=I();try{O.get(a)(b,c,e,f)}catch(l){L(g);if(l!==l+0&&"longjmp"!==l)throw l;Z(1,0)}}function Nb(a,b,c){var e=I();try{O.get(a)(b,c)}catch(f){L(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Kb(a,b,c,e,f,g,l,p,r){var n=I();try{return O.get(a)(b,c,e,f,g,l,p,r)}catch(q){L(n);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}function Pb(a,b,c,e,f,g,l,p,r,n){var q=I();try{Rb(a,b,c,e,f,g,l,p,r,n)}catch(v){L(q);if(v!==v+0&&"longjmp"!==v)throw v;Z(1,0)}}
function Lb(a,b,c,e,f,g,l,p){var r=I();try{return Sb(a,b,c,e,f,g,l,p)}catch(n){L(r);if(n!==n+0&&"longjmp"!==n)throw n;Z(1,0)}}d.ccall=va;d.cwrap=function(a,b,c,e){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!e?ua(a):function(){return va(a,b,c,arguments,e)}};
d.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":H[a>>0]=b;break;case "i8":H[a>>0]=b;break;case "i16":Ga[a>>1]=b;break;case "i32":N[a>>2]=b;break;case "i64":S=[b>>>0,(R=b,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[a>>2]=S[0];N[a+4>>2]=S[1];break;case "float":Ha[a>>2]=b;break;case "double":Ia[a>>3]=b;break;default:C("invalid type for setValue: "+c)}};
d.writeAsciiToMemory=Ca;d.FS=W;var Tb;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ra=function Ub(){Tb||Vb();Tb||(Ra=Ub)};
function Vb(a){function b(){if(!Tb&&(Tb=!0,d.calledRun=!0,!ta)){d.noFSInit||W.Ua.rb||W.Ua();W.Sb=!1;Za(Ka);Za(La);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Wb){var c=a,e=d._main;c=c||[];var f=c.length+1,g=wa(4*(f+1));N[g>>2]=Ba(ia);for(var l=1;l<f;l++)N[(g>>2)+l]=Ba(c[l-1]);N[(g>>2)+f]=0;try{var p=e(f,g);da(p,!0)}catch(r){r instanceof ca||"unwind"==r||((c=r)&&"object"===typeof r&&r.stack&&(c=[r,r.stack]),h("exception thrown: "+c),ja(1,r))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&
(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Na.unshift(c);Za(Na)}}a=a||ha;if(!(0<P)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Oa();Za(Ja);0<P||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Vb;function da(a,b){if(!b||!(noExitRuntime||0<$a)||0!==a){if(!(noExitRuntime||0<$a)){Za(Ma);W.quit();if(d.onExit)d.onExit(a);ta=!0}ja(a,new ca(a))}}
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Wb=!1;d.noInitialRun&&(Wb=!1);Vb();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
